play.http.secret.key=">WHknlCprTkSFP20JUhwNaF8CG>lM3v:SuQbWUVJ`]Vd2:BRUdXwDM9fmyEgP:_4"
play.i18n.langs=[ "en" ]
play.filters.disabled += "play.filters.csrf.CSRFFilter"
play.server.websocket.periodic-keep-alive-max-idle = 10 seconds

requester {
  ssl = "false"
  nsi {
    requesterNsa = "urn:ogf:network:internet2.edu:2025:nsa:nsi-requester"
    providers = [
      { id = "urn:ogf:network:internet2.edu:2025:nsa:supa"
        url = "https://nsi.testing.ns.internet2.edu/soap/connection/provider"
        portPrefix = "urn:ogf:network:internet2.edu:2025:topology:"
      }
    ]
  }
}
play.filters.hosts {
  allowed = ["."]
}
ws.ssl {
  default = false
  keyManager = {
    stores = [
      { path: "config/keystore.jks", type: "JKS", password: "secret" }
    ]
  }
  trustManager = {
    stores = [
      { path: "config/truststore.jks", type: "JKS", password = "secret" }
    ]
  }
}